<CFPARAM NAME=Attributes.Mode DEFAULT=1>
<CFPARAM NAME=Attributes.CaseID DEFAULT=0> 
<CFPARAM NAME=Attributes.SiteID DEFAULT=0> 
<CFPARAM NAME=Attributes.ClaimID DEFAULT="">
<CFPARAM NAME=Attributes.DerivativeCode DEFAULT="">
<CFPARAM NAME=Attributes.MsgBody DEFAULT="">
<CFPARAM NAME=Attributes.dtcall DEFAULT="">
<CFPARAM NAME=Attributes.MRCPART DEFAULT=0>

<CFTRY>
<CFSTOREDPROC PROCEDURE="sspPDB_ICAP" DATASOURCE=#Request.MTRDSN# RETURNCODE=YES>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_INTEGER VALUE=#Attributes.Mode# DBVARNAME=@ai_mode>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_INTEGER VALUE=#Attributes.CaseID# DBVARNAME=@ai_caseid>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_INTEGER VALUE=#Attributes.SiteID# DBVARNAME=@ai_SiteID>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_VARCHAR VALUE=#Attributes.ClaimID# DBVARNAME=@aa_ClaimID>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_VARCHAR VALUE="#Attributes.DerivativeCode#" DBVARNAME=@as_vaDerivativeCode>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_VARCHAR VALUE="#Attributes.MsgBody#" DBVARNAME=@as_vaBody>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_TIMESTAMP NULL=YES DBVARNAME=@adt_dtcall>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_INTEGER VALUE="#Attributes.MRCPART#" DBVARNAME=@ai_iMRCPART>
</CFSTOREDPROC>
<CFSET returncode = CFSTOREDPROC.StatusCode>
<CFIF returncode LT 0>
	<CFTHROW TYPE=EX_DBERROR ErrorCode="PDB_ICAP(#returncode#)">
</CFIF>
<CFCATCH>
	<CFRETHROW>
</CFCATCH>
</CFTRY>