<CFPROCESSINGDIRECTIVE pageencoding = "utf-8">

<CFPARAM NAME=Attributes.Mode DEFAULT=1>
<CFPARAM NAME=Attributes.DomainID DEFAULT=314> <!--- IntMultiLog --->
<CFPARAM NAME=Attributes.IOBJID DEFAULT=0>
<CFPARAM NAME=Attributes.Key DEFAULT="">
<CFPARAM NAME=Attributes.Value DEFAULT="">

<CFTRY>
<CFSTOREDPROC PROCEDURE="sspINTMultiLog" DATASOURCE=#Request.MTRDSN# RETURNCODE=YES>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_INTEGER VALUE=#Attributes.Mode# DBVARNAME=@ai_mode>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_INTEGER VALUE=#Attributes.DomainID# DBVARNAME=@ai_domainid>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_INTEGER VALUE=#Attributes.IOBJID# DBVARNAME=@ai_objid>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_VARCHAR VALUE="#Attributes.Key#" DBVARNAME=@as_key>
	<CFPROCPARAM TYPE=IN CFSQLTYPE=CF_SQL_VARCHAR VALUE="#Attributes.Value#" DBVARNAME=@as_value>
</CFSTOREDPROC>
<CFSET returncode = CFSTOREDPROC.StatusCode>
<CFIF returncode LT 0>
	<CFTHROW TYPE=EX_DBERROR ErrorCode="INTMultiLog(#returncode#)">
</CFIF>
<CFCATCH>
	<CFRETHROW>
</CFCATCH>
</CFTRY>